import { socialLinks } from "@/lib/social-links"

export const siteConfig = {
  name: "Islam I. Abdulaal",
  title: "Islam I. Abdulaal | Photonics Research",
  description:
    "Personal website of Islam I. Abdulaal — postgraduate student focused on integrated, neuromorphic, quantum, nonlinear, and computational photonics.",
  url: "https://iabdul-aal.github.io",
  locale: "en_US",
  ogImage: "/personal-pic.png",
  keywords: [
    "Islam I. Abdulaal",
    "integrated photonics",
    "silicon photonics",
    "neuromorphic photonics",
    "photonic neural networks",
    "integrated quantum photonics",
    "nonlinear quantum photonics",
    "quantum photonics",
    "nonlinear optics",
    "nanophotonics",
    "metasurfaces",
    "computational photonics",
    "photonic design",
    "waveguide engineering",
    "PINNs",
    "SPDC",
    "quasi-BIC",
    "Optica",
    "Alexandria University",
    "A*STAR",
    "NanoPhoto Lab",
    "HW Carnival",
    "Si-Cast",
    "Si-Clash",
    "AlexDuino",
    "metamaterials",
    "BICs",
    "2D-materials",
  ],
  sameAs: [
    socialLinks.linkedin,
    socialLinks.twitter,
    socialLinks.github,
    socialLinks.orcid,
    socialLinks.scholar,
    socialLinks.semanticScholar,
    socialLinks.researchGate,
    socialLinks.medium,
    socialLinks.arxiv,
    socialLinks.optica,
  ],
} as const

export const personConfig = {
  name: "Islam I. Abdulaal",
  givenName: "Islam",
  familyName: "Abdulaal",
  role: "Postgraduate Student",
  affiliation: "Alexandria University",
  lab: "NanoPhoto Lab, A*STAR",
  location: "Alexandria, Egypt",
  email: socialLinks.email,
  phone: socialLinks.phone,
  orcid: "0009-0004-9300-3936",
  focusAreas: [
    "Integrated photonics",
    "Silicon photonics",
    "Neuromorphic photonics",
    "Quantum photonics",
    "Nanophotonics",
    "Computational photonics",
    "Physics-informed machine learning",
    "Metamaterials",
    "Bound states in the continuum (BICs)",
  ],
} as const
