export const socialLinks = {
  linkedin: "https://www.linkedin.com/in/iabdul-aal",
  github: "https://github.com/iabdul-aal",
  orcid: "https://orcid.org/0009-0004-9300-3936",
  scholar: "https://scholar.google.com/citations?user=CPmqNv4AAAAJ&hl=en",
  semanticScholar: "https://www.semanticscholar.org/author/Islam-I.-Abdulaal",
  researchGate: "https://www.researchgate.net/profile/Islam-Abdulaal",
  academia: "https://alex.academia.edu/IslamAbdulaal",
  frontiersLoop: "https://loop.frontiersin.org/people/3361076/overview",
  sciprofiles: "https://sciprofiles.com/profile/iabdul-aal",
  collabratec: "https://collabratec.ieee.org/iabdul-aal",
  medium: "https://medium.com/@iabdul-aal",
  twitter: "https://x.com/iabdul_aal",
  bluesky: "https://iabdul-aal.bsky.social",
  telegram: "https://t.me/iabdul_aal",
  linktree: "https://linktr.ee/iabdul-aal",
  gravatar: "https://gravatar.com/iabdul-aal",
  f6s: "https://www.f6s.com/iabdul-aal",
  arxiv: "https://arxiv.org/abs/2510.00357",
  nanophoto: "https://www.nanophoto.sg/team",
  email: "iabdul-aal@ieee.org",
  academicEmail: "eslam.ibrahim2026@alexu.edu.eg",
  phone: "+20120460921",
  whatsapp: "https://wa.me/20120460921",
}

export const professionalProfiles = {
  ieeeCollabratec: socialLinks.collabratec,
  scholar: socialLinks.scholar,
  semanticscholar: socialLinks.semanticScholar,
  researchGate: socialLinks.researchGate,
  academia: socialLinks.academia,
  loop: socialLinks.frontiersLoop,
  sciprofiles: socialLinks.sciprofiles,
  orcid: socialLinks.orcid,
}

export const contactInfo = {
  email: socialLinks.email,
  secondaryEmail: socialLinks.academicEmail,
  phone: socialLinks.phone,
  whatsapp: socialLinks.whatsapp,
  location: "Alexandria, Egypt",
  timezone: "EET (UTC+2)",
  webOfScienceResearcherID: "OLP-9224-2025",
}
